import type { NewTaskDto, TaskDto } from './generated/tasks/typescript/index.js';

export interface TasksSdkOptions {
  baseUrl: string;
  fetch?: typeof fetch;
}

/**
 * Hand-written client over the `tasks` contract. The request/response shapes
 * (`TaskDto`, `NewTaskDto`) are generated by `@kurotako/gen-typescript` from
 * `openapi.json`; only the HTTP wiring below is written by hand, since the IR
 * carries schemas, not operations.
 */
export class TasksSdk {
  private readonly baseUrl: string;
  private readonly fetch: typeof fetch;

  constructor(options: TasksSdkOptions) {
    this.baseUrl = options.baseUrl.replace(/\/$/, '');
    this.fetch = options.fetch ?? globalThis.fetch;
  }

  async listTasks(): Promise<TaskDto[]> {
    return this.request<TaskDto[]>('GET', '/tasks');
  }

  async getTask(id: string): Promise<TaskDto> {
    return this.request<TaskDto>('GET', `/tasks/${encodeURIComponent(id)}`);
  }

  async createTask(task: NewTaskDto): Promise<TaskDto> {
    return this.request<TaskDto>('POST', '/tasks', task);
  }

  private async request<T>(
    method: string,
    path: string,
    body?: unknown,
  ): Promise<T> {
    const response = await this.fetch(`${this.baseUrl}${path}`, {
      method,
      headers: body === undefined ? {} : { 'content-type': 'application/json' },
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    if (!response.ok) {
      throw new Error(`${method} ${path} failed with status ${response.status}`);
    }
    return (await response.json()) as T;
  }
}
