import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// The API category is generated by docusaurus-plugin-typedoc into
// `docs/api/typedoc-sidebar.cjs`. On a clean checkout that file does not exist
// until the first build; fall back to an empty slice so `sidebars.ts` still
// evaluates (the plugin regenerates it before the docs plugin reads sidebars on
// subsequent builds).
let typedocSidebar: unknown[] = [];
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const generated = require('./docs/api/typedoc-sidebar.cjs');
  typedocSidebar = Array.isArray(generated)
    ? generated
    : (generated?.items ?? []);
} catch {
  typedocSidebar = [];
}

const sidebars: SidebarsConfig = {
  guide: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: ['getting-started/quick-start', 'getting-started/installation'],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/parsers-and-generators',
        'concepts/intermediate-representation',
        'concepts/dependency-graph',
        'concepts/namespaces',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/tako-config',
        'reference/cli',
        'reference/catalog',
        'reference/output-modes',
      ],
    },
    // The generated API category is appended only when TypeDoc has produced its
    // sidebar slice (Docusaurus rejects a category with no items).
    ...(typedocSidebar.length > 0
      ? [
          {
            type: 'category' as const,
            label: 'API',
            items: typedocSidebar as never,
          },
        ]
      : []),
  ],
};

export default sidebars;
