import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import type { SourceIR } from '@kurotako/ir';
import { createSourceIR } from '@kurotako/ir';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { DriverError, OutputCollisionError } from './errors.js';
import { run } from './run.js';
import type {
  Generator,
  GeneratorArtifact,
  Parser,
  ResolvedConfig,
} from './types.js';

function source(namespace: string): SourceIR {
  return createSourceIR({ namespace, parser: 'fake' })
    .addEntity('User', (e) => {
      e.field('id', (f) => f.scalar('uuid').primary());
    })
    .build();
}

function parser(namespace: string): Parser {
  return { name: `parser-${namespace}`, parse: () => source(namespace) };
}

function generator(
  name: string,
  opts?: {
    dependsOn?: string[];
    optionalDependsOn?: string[];
    onGenerate?: (deps: Record<string, GeneratorArtifact>) => void;
    throws?: boolean;
  },
): Generator {
  return {
    name,
    dependsOn: opts?.dependsOn,
    optionalDependsOn: opts?.optionalDependsOn,
    generate: ({ dependencies }) => {
      if (opts?.throws) {
        throw new Error('kaboom');
      }
      opts?.onGenerate?.(dependencies);
      return {
        files: [{ path: `pg/${name}/index.ts`, content: `// ${name}\n` }],
        artifact: { entities: {} },
      };
    },
  };
}

let dir: string;

beforeEach(async () => {
  dir = await fs.mkdtemp(path.join(os.tmpdir(), 'kurotako-run-'));
});

afterEach(async () => {
  await fs.rm(dir, { recursive: true, force: true });
});

function config(overrides: Partial<ResolvedConfig>): ResolvedConfig {
  return {
    rootDir: dir,
    sources: { pg: { parser: parser('pg') } },
    generators: { zod: { generator: generator('zod') } },
    outputs: [{ dir }],
    ...overrides,
  };
}

describe('run', () => {
  it('write: false produces a full RunResult and touches no disk', async () => {
    const result = await run(config({}), { write: false });
    expect(result.order).toEqual(['zod']);
    expect(result.files.map((f) => f.path)).toEqual([
      'pg/index.ts',
      'pg/zod/index.ts',
    ]);
    expect(result.ir.sources.pg).toBeDefined();
    expect(result.artifacts.zod).toBeDefined();
    expect(result.written).toEqual([]);
    expect(await fs.readdir(dir)).toEqual([]);
  });

  it('plan: true populates RunResult.plan, skips afterEmit, and writes nothing', async () => {
    const afterEmit = vi.fn();
    const result = await run(config({ hooks: { afterEmit } }), { plan: true });

    expect(result.plan?.map((p) => path.relative(dir, p.path)).sort()).toEqual([
      '.gitattributes',
      'pg/index.ts',
      'pg/zod/index.ts',
    ]);
    expect(
      result.plan?.find((p) => p.path.endsWith('pg/zod/index.ts'))?.content,
    ).toBe('// Generated by tako. Do not edit.\n// zod\n');
    expect(result.written).toEqual([]);
    expect(afterEmit).not.toHaveBeenCalled();
    expect(await fs.readdir(dir)).toEqual([]);
  });

  it('plan: true still throws IrValidationError on an invalid IR', async () => {
    const bad: Parser = {
      name: 'p',
      parse: () => ({ namespace: 'pg', parser: 'p' }) as unknown as SourceIR,
    };
    const cfg = config({ sources: { pg: { parser: bad } } });
    await expect(run(cfg, { plan: true })).rejects.toMatchObject({
      code: 'ir_invalid',
    });
  });

  it('a real run writes the tree, then afterEmit fires once with written paths', async () => {
    const afterEmit = vi.fn();
    await run(config({ hooks: { afterEmit } }));
    expect(await fs.readFile(path.join(dir, 'pg/zod/index.ts'), 'utf8')).toBe(
      '// Generated by tako. Do not edit.\n// zod\n',
    );
    expect(await fs.readFile(path.join(dir, 'pg/index.ts'), 'utf8')).toBe(
      "// Generated by tako. Do not edit.\nexport * from './zod';\n",
    );
    expect(afterEmit).toHaveBeenCalledTimes(1);
    const ctx = afterEmit.mock.calls[0]?.[0] as {
      files: string[];
      outputDir: string;
    };
    expect(ctx.files).toContain(path.join(dir, 'pg/zod/index.ts'));
    expect(ctx.outputDir).toBe(dir);
  });

  it('a generator throw becomes a DriverError naming it', async () => {
    const cfg = config({
      generators: { zod: { generator: generator('zod', { throws: true }) } },
    });
    await expect(run(cfg, { write: false })).rejects.toMatchObject({
      code: 'driver_error',
      role: 'generator',
      driverName: 'zod',
    });
    await expect(run(cfg, { write: false })).rejects.toBeInstanceOf(
      DriverError,
    );
  });

  it('a parser throw becomes a DriverError naming it and its namespace', async () => {
    const cfg = config({
      sources: {
        pg: {
          parser: {
            name: 'prisma',
            parse: () => {
              throw new Error('schema not found');
            },
          },
        },
      },
    });
    await expect(run(cfg, { write: false })).rejects.toMatchObject({
      code: 'driver_error',
      role: 'parser',
      driverName: 'prisma',
      namespace: 'pg',
    });
    await expect(run(cfg, { write: false })).rejects.toBeInstanceOf(
      DriverError,
    );
  });

  it('dependencies holds only declared, present deps', async () => {
    const seen: Record<string, string[]> = {};
    const cfg = config({
      generators: {
        zod: { generator: generator('zod') },
        angular: {
          generator: generator('angular', {
            dependsOn: ['zod'],
            optionalDependsOn: ['prisma-dmmf'],
            onGenerate: (deps) => {
              seen.angular = Object.keys(deps);
            },
          }),
        },
      },
    });
    const result = await run(cfg, { write: false });
    expect(result.order).toEqual(['zod', 'angular']);
    expect(seen.angular).toEqual(['zod']);
  });

  it('rejects before parsing when opts.signal is already aborted', async () => {
    const controller = new AbortController();
    controller.abort();
    let parsed = false;
    const cfg = config({
      sources: {
        pg: {
          parser: {
            name: 'p',
            parse: () => {
              parsed = true;
              return source('pg');
            },
          },
        },
      },
    });
    await expect(run(cfg, { signal: controller.signal })).rejects.toThrow();
    expect(parsed).toBe(false);
  });

  it('a generator emitting <ns>/index.ts collides with the synthesized barrel', async () => {
    const stray: Generator = {
      name: 'zod',
      generate: () => ({
        files: [
          { path: 'pg/zod/user.ts', content: '// user\n' },
          { path: 'pg/index.ts', content: '// stray\n' },
        ],
        artifact: { entities: {} },
      }),
    };
    const cfg = config({ generators: { zod: { generator: stray } } });
    await expect(run(cfg, { write: false })).rejects.toBeInstanceOf(
      OutputCollisionError,
    );
    await expect(run(cfg, { write: false })).rejects.toThrow(
      /<namespace>\/<generatorName>/,
    );
  });

  it('synthesizes a root barrel across two generators on one namespace', async () => {
    const cfg = config({
      generators: {
        zod: { generator: generator('zod') },
        angular: { generator: generator('angular', { dependsOn: ['zod'] }) },
      },
    });
    const result = await run(cfg, { write: false });
    const barrel = result.files.find((f) => f.path === 'pg/index.ts');
    expect(barrel?.content).toBe(
      "// Generated by tako. Do not edit.\nexport * from './angular';\nexport * from './zod';\n",
    );
  });

  it('two outputs with disjoint generators filters each write only their own subset', async () => {
    const dirA = path.join(dir, 'a');
    const dirB = path.join(dir, 'b');
    const cfg = config({
      generators: {
        zod: { generator: generator('zod') },
        angular: { generator: generator('angular') },
      },
      outputs: [
        { dir: dirA, generators: ['zod'] },
        { dir: dirB, generators: ['zod', 'angular'] },
      ],
    });
    const result = await run(cfg);

    expect(result.written).toHaveLength(2);
    expect(result.written[0]?.output.dir).toBe(dirA);
    expect(result.written[1]?.output.dir).toBe(dirB);

    await expect(fs.access(path.join(dirA, 'pg', 'angular'))).rejects.toThrow();
    expect(await fs.readFile(path.join(dirA, 'pg', 'index.ts'), 'utf8')).toBe(
      "// Generated by tako. Do not edit.\nexport * from './zod';\n",
    );
    expect(await fs.readFile(path.join(dirB, 'pg', 'index.ts'), 'utf8')).toBe(
      "// Generated by tako. Do not edit.\nexport * from './angular';\nexport * from './zod';\n",
    );

    // The full computed tree stays unfiltered regardless of any output's filter.
    expect(result.files.map((f) => f.path).sort()).toEqual([
      'pg/angular/index.ts',
      'pg/index.ts',
      'pg/zod/index.ts',
    ]);
    expect(Object.keys(result.artifacts).sort()).toEqual(['angular', 'zod']);
  });

  it('an output with generators omitted gets every generator that ran', async () => {
    const outDir = path.join(dir, 'out');
    const cfg = config({
      generators: {
        zod: { generator: generator('zod') },
        angular: { generator: generator('angular') },
      },
      outputs: [{ dir: outDir }],
    });
    await run(cfg);
    expect(await fs.readFile(path.join(outDir, 'pg', 'index.ts'), 'utf8')).toBe(
      "// Generated by tako. Do not edit.\nexport * from './angular';\nexport * from './zod';\n",
    );
  });

  it('afterEmit fires once per output, in config.outputs order, each call scoped to its own output', async () => {
    const calls: { outputDir: string; files: string[] }[] = [];
    const afterEmit = vi.fn((ctx: { outputDir: string; files: string[] }) => {
      calls.push({ outputDir: ctx.outputDir, files: ctx.files });
    });
    const dirA = path.join(dir, 'a');
    const dirB = path.join(dir, 'b');
    const cfg = config({
      outputs: [{ dir: dirA }, { dir: dirB }],
      hooks: { afterEmit },
    });
    await run(cfg);

    expect(afterEmit).toHaveBeenCalledTimes(2);
    expect(calls[0]?.outputDir).toBe(dirA);
    expect(calls[1]?.outputDir).toBe(dirB);
    expect(calls[0]?.files.every((f) => f.startsWith(dirA))).toBe(true);
    expect(calls[1]?.files.every((f) => f.startsWith(dirB))).toBe(true);
  });

  it('a HookError thrown for output 1 of 2 stops output 2 from being written', async () => {
    const dirA = path.join(dir, 'a');
    const dirB = path.join(dir, 'b');
    let calls = 0;
    const afterEmit = vi.fn(() => {
      calls += 1;
      if (calls === 1) {
        throw new Error('boom');
      }
    });
    const cfg = config({
      outputs: [{ dir: dirA }, { dir: dirB }],
      hooks: { afterEmit },
    });

    await expect(run(cfg)).rejects.toMatchObject({ code: 'hook_error' });
    expect(
      await fs.access(dirA).then(
        () => true,
        () => false,
      ),
    ).toBe(true);
    expect(
      await fs.access(dirB).then(
        () => true,
        () => false,
      ),
    ).toBe(false);
  });
});
