import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import type { SourceIR } from '@kurotako/ir';
import { createSourceIR } from '@kurotako/ir';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import {
  DriverError,
  OutputCollisionError,
  OutputPeerConflictError,
  SegmentViolationError,
} from './errors.js';
import { run } from './run.js';
import type {
  GenerateContext,
  Generator,
  GeneratorArtifact,
  Parser,
  ResolvedConfig,
} from './types.js';

function source(namespace: string): SourceIR {
  return createSourceIR({ namespace, parser: 'fake' })
    .addEntity('User', (e) => {
      e.field('id', (f) => f.scalar('uuid').primary());
    })
    .build();
}

function parser(namespace: string): Parser {
  return { name: `parser-${namespace}`, parse: () => source(namespace) };
}

function generator(
  name: string,
  opts?: {
    dependsOn?: Generator[];
    onGenerate?: (
      deps: Record<string, GeneratorArtifact>,
      ctx: GenerateContext,
    ) => void;
    throws?: boolean;
    peers?: Record<string, string>;
    /** Extra path, relative to the output root, emitted next to the index. */
    extraFile?: string;
  },
): Generator {
  return {
    name,
    dependsOn: opts?.dependsOn,
    generate: (ctx) => {
      if (opts?.throws) {
        throw new Error('kaboom');
      }
      opts?.onGenerate?.(ctx.dependencies, ctx);
      const files = Object.keys(ctx.ir.sources).map((namespace) => ({
        path: `${namespace}/${ctx.segment}/index.ts`,
        content: `// ${ctx.segment}\n`,
      }));
      if (opts?.extraFile) {
        files.push({ path: opts.extraFile, content: '// extra\n' });
      }
      return {
        files,
        artifact: { entities: {}, peerDependencies: opts?.peers },
      };
    },
  };
}

let dir: string;

beforeEach(async () => {
  dir = await fs.mkdtemp(path.join(os.tmpdir(), 'kurotako-run-'));
});

afterEach(async () => {
  await fs.rm(dir, { recursive: true, force: true });
});

function config(overrides: Partial<ResolvedConfig>): ResolvedConfig {
  return {
    rootDir: dir,
    sources: { pg: { parser: parser('pg') } },
    generators: { zod: { generator: generator('zod') } },
    outputs: [{ dir }],
    ...overrides,
  };
}

describe('run', () => {
  it('write: false produces a full RunResult and touches no disk', async () => {
    const result = await run(config({}), { write: false });
    expect(result.order).toEqual(['zod']);
    expect(result.files.map((f) => f.path)).toEqual([
      'pg/index.ts',
      'pg/zod/index.ts',
    ]);
    expect(result.ir.sources.pg).toBeDefined();
    expect(result.artifacts.zod).toBeDefined();
    expect(result.written).toEqual([]);
    expect(await fs.readdir(dir)).toEqual([]);
  });

  it('plan: true populates RunResult.plan, skips afterEmit, and writes nothing', async () => {
    const afterEmit = vi.fn();
    const result = await run(config({ hooks: { afterEmit } }), { plan: true });

    expect(result.plan?.map((p) => path.relative(dir, p.path)).sort()).toEqual([
      '.gitattributes',
      'pg/index.ts',
      'pg/zod/index.ts',
    ]);
    expect(
      result.plan?.find((p) => p.path.endsWith('pg/zod/index.ts'))?.content,
    ).toBe('// Generated by tako. Do not edit.\n// zod\n');
    expect(result.written).toEqual([]);
    expect(afterEmit).not.toHaveBeenCalled();
    expect(await fs.readdir(dir)).toEqual([]);
  });

  it('plan: true still throws IrValidationError on an invalid IR', async () => {
    const bad: Parser = {
      name: 'p',
      parse: () => ({ namespace: 'pg', parser: 'p' }) as unknown as SourceIR,
    };
    const cfg = config({ sources: { pg: { parser: bad } } });
    await expect(run(cfg, { plan: true })).rejects.toMatchObject({
      code: 'ir_invalid',
    });
  });

  it('a real run writes the tree, then afterEmit fires once with written paths', async () => {
    const afterEmit = vi.fn();
    await run(config({ hooks: { afterEmit } }));
    expect(await fs.readFile(path.join(dir, 'pg/zod/index.ts'), 'utf8')).toBe(
      '// Generated by tako. Do not edit.\n// zod\n',
    );
    expect(await fs.readFile(path.join(dir, 'pg/index.ts'), 'utf8')).toBe(
      "// Generated by tako. Do not edit.\nexport * from './zod/index.js';\n",
    );
    expect(afterEmit).toHaveBeenCalledTimes(1);
    const ctx = afterEmit.mock.calls[0]?.[0] as {
      files: string[];
      outputDir: string;
    };
    expect(ctx.files).toContain(path.join(dir, 'pg/zod/index.ts'));
    expect(ctx.outputDir).toBe(dir);
  });

  it('a generator throw becomes a DriverError naming it', async () => {
    const cfg = config({
      generators: { zod: { generator: generator('zod', { throws: true }) } },
    });
    await expect(run(cfg, { write: false })).rejects.toMatchObject({
      code: 'driver_error',
      role: 'generator',
      driverName: 'zod',
    });
    await expect(run(cfg, { write: false })).rejects.toBeInstanceOf(
      DriverError,
    );
  });

  it('a parser throw becomes a DriverError naming it and its namespace', async () => {
    const cfg = config({
      sources: {
        pg: {
          parser: {
            name: 'prisma',
            parse: () => {
              throw new Error('schema not found');
            },
          },
        },
      },
    });
    await expect(run(cfg, { write: false })).rejects.toMatchObject({
      code: 'driver_error',
      role: 'parser',
      driverName: 'prisma',
      namespace: 'pg',
    });
    await expect(run(cfg, { write: false })).rejects.toBeInstanceOf(
      DriverError,
    );
  });

  it('runs generators in declaration order', async () => {
    const cfg = config({
      generators: {
        angular: { generator: generator('angular') },
        zod: { generator: generator('zod') },
      },
    });
    const result = await run(cfg, { write: false });
    expect(result.order).toEqual(['angular', 'zod']);
  });

  describe('private generator dependencies', () => {
    it('runs the dependency first, with segment <name>/<dep> and the dependent namespaces', async () => {
      const calls: string[] = [];
      const seen: { segment: string; namespaces: string[] }[] = [];
      const zod = generator('zod', {
        onGenerate: (_deps, ctx) => {
          calls.push('zod');
          seen.push({
            segment: ctx.segment,
            namespaces: Object.keys(ctx.ir.sources),
          });
        },
      });
      const angular = generator('angular', {
        dependsOn: [zod],
        onGenerate: (deps, ctx) => {
          calls.push('angular');
          seen.push({
            segment: ctx.segment,
            namespaces: Object.keys(ctx.ir.sources),
          });
          expect(Object.keys(deps)).toEqual(['zod']);
        },
      });
      await run(
        config({
          generators: { angular: { generator: angular } },
        }),
        { write: false },
      );
      expect(calls).toEqual(['zod', 'angular']);
      expect(seen).toEqual([
        { segment: 'angular/zod', namespaces: ['pg'] },
        { segment: 'angular', namespaces: ['pg'] },
      ]);
    });

    it('a private instance covers exactly its dependent namespaces', async () => {
      const namespaces: string[][] = [];
      const zod = generator('zod', {
        onGenerate: (_deps, ctx) => {
          namespaces.push(Object.keys(ctx.ir.sources));
        },
      });
      await run(
        config({
          sources: {
            pg: { parser: parser('pg') },
            api: { parser: parser('api') },
          },
          generators: {
            angular: {
              generator: generator('angular', { dependsOn: [zod] }),
              namespaces: ['api'],
            },
          },
        }),
        { write: false },
      );
      expect(namespaces).toEqual([['api']]);
    });

    it('exposes the dependency artifact under its driver name', async () => {
      const zod: Generator = {
        name: 'zod',
        generate: (ctx) => ({
          files: [{ path: `pg/${ctx.segment}/index.ts`, content: '// zod\n' }],
          artifact: { entities: {}, extra: { marker: 42 } },
        }),
      };
      let extra: unknown;
      const angular = generator('angular', {
        dependsOn: [zod],
        onGenerate: (deps) => {
          extra = deps.zod?.extra;
        },
      });
      await run(config({ generators: { angular: { generator: angular } } }), {
        write: false,
      });
      expect(extra).toEqual({ marker: 42 });
    });

    it('attributes private files to the dependent and keeps them under outputs[].generators', async () => {
      const cfg = config({
        generators: {
          angular: {
            generator: generator('angular', {
              dependsOn: [generator('zod')],
            }),
          },
          typescript: { generator: generator('typescript') },
        },
        outputs: [{ dir, generators: ['angular'] }],
      });
      const result = await run(cfg, { write: false, plan: true });
      expect(
        result.plan
          ?.map((f) => path.relative(dir, f.path))
          .filter((p) => p !== '.gitattributes'),
      ).toEqual([
        'pg/angular/index.ts',
        'pg/angular/zod/index.ts',
        'pg/index.ts',
      ]);
    });

    it('keeps private artifacts out of RunResult.artifacts', async () => {
      const result = await run(
        config({
          generators: {
            angular: {
              generator: generator('angular', {
                dependsOn: [generator('zod')],
              }),
            },
          },
        }),
        { write: false },
      );
      expect(Object.keys(result.artifacts)).toEqual(['angular']);
      expect(result.order).toEqual(['angular']);
    });

    it('does not re-export the private sub-tree from the root barrel and coexists with a user zod', async () => {
      const warn = vi.fn();
      const logger = { debug() {}, info() {}, warn, error() {} };
      const result = await run(
        config({
          generators: {
            angular: {
              generator: generator('angular', {
                dependsOn: [generator('zod')],
              }),
            },
            zod: { generator: generator('zod') },
          },
        }),
        { write: false, logger },
      );
      expect(result.files.map((f) => f.path)).toEqual([
        'pg/angular/index.ts',
        'pg/angular/zod/index.ts',
        'pg/index.ts',
        'pg/zod/index.ts',
      ]);
      const barrel = result.files.find((f) => f.path === 'pg/index.ts');
      expect(barrel?.content).toBe(
        "// Generated by tako. Do not edit.\nexport * from './angular/index.js';\nexport * from './zod/index.js';\n",
      );
      expect(warn).not.toHaveBeenCalled();
    });

    it('nests segments through a chain of dependencies (a/b/c)', async () => {
      const segments: string[] = [];
      const record = (_deps: unknown, ctx: GenerateContext) => {
        segments.push(ctx.segment);
      };
      const c = generator('c', { onGenerate: record });
      const b = generator('b', { dependsOn: [c], onGenerate: record });
      const a = generator('a', { dependsOn: [b], onGenerate: record });
      const result = await run(
        config({ generators: { a: { generator: a } } }),
        {
          write: false,
        },
      );
      expect(segments).toEqual(['a/b/c', 'a/b', 'a']);
      expect(result.files.map((f) => f.path)).toEqual([
        'pg/a/b/c/index.ts',
        'pg/a/b/index.ts',
        'pg/a/index.ts',
        'pg/index.ts',
      ]);
    });

    it('gives each dependent its own copy when two generators depend on the same driver', async () => {
      const result = await run(
        config({
          generators: {
            a: { generator: generator('a', { dependsOn: [generator('zod')] }) },
            b: { generator: generator('b', { dependsOn: [generator('zod')] }) },
          },
        }),
        { write: false },
      );
      expect(result.files.map((f) => f.path)).toEqual([
        'pg/a/index.ts',
        'pg/a/zod/index.ts',
        'pg/b/index.ts',
        'pg/b/zod/index.ts',
        'pg/index.ts',
      ]);
    });

    it('merges private peerDependencies into the dependent artifact', async () => {
      const result = await run(
        config({
          generators: {
            angular: {
              generator: generator('angular', {
                peers: { '@angular/core': '^22', zod: '^4' },
                dependsOn: [generator('zod', { peers: { zod: '^4' } })],
              }),
            },
          },
        }),
        { write: false },
      );
      expect(result.artifacts.angular?.peerDependencies).toEqual({
        '@angular/core': '^22',
        zod: '^4',
      });
    });

    it('takes the private peers when the dependent declares none', async () => {
      const result = await run(
        config({
          generators: {
            angular: {
              generator: generator('angular', {
                dependsOn: [generator('zod', { peers: { zod: '^4' } })],
              }),
            },
          },
        }),
        { write: false },
      );
      expect(result.artifacts.angular?.peerDependencies).toEqual({ zod: '^4' });
    });

    it('throws OutputPeerConflictError naming the dependent on a range conflict', async () => {
      const cfg = config({
        generators: {
          angular: {
            generator: generator('angular', {
              peers: { zod: '^3' },
              dependsOn: [generator('zod', { peers: { zod: '^4' } })],
            }),
          },
        },
      });
      const error = await run(cfg, { write: false }).catch((e) => e);
      expect(error).toBeInstanceOf(OutputPeerConflictError);
      expect(error).toMatchObject({
        package: 'zod',
        ranges: ['^3', '^4'],
        generators: ['angular', 'zod'],
        dependent: 'angular',
      });
      expect(error.message).toContain("generator 'angular'");
    });

    it('throws SegmentViolationError when a private instance emits outside its segment', async () => {
      const stray: Generator = {
        name: 'zod',
        generate: () => ({
          files: [{ path: 'pg/zod/index.ts', content: '// hardcoded\n' }],
          artifact: { entities: {} },
        }),
      };
      const cfg = config({
        generators: {
          angular: { generator: generator('angular', { dependsOn: [stray] }) },
        },
      });
      const error = await run(cfg, { write: false }).catch((e) => e);
      expect(error).toBeInstanceOf(SegmentViolationError);
      expect(error).toMatchObject({
        code: 'segment_violation',
        generator: 'zod',
        path: 'pg/zod/index.ts',
        expected: '<namespace>/angular/zod/',
      });
    });

    it('does not apply the segment guard to top-level generators', async () => {
      const cfg = config({
        generators: {
          zod: {
            generator: generator('zod', { extraFile: 'pg/elsewhere/x.ts' }),
          },
        },
      });
      await expect(run(cfg, { write: false })).resolves.toBeDefined();
    });

    it('wraps a private failure in a DriverError naming the dependency and its dependent', async () => {
      const cfg = config({
        generators: {
          angular: {
            generator: generator('angular', {
              dependsOn: [generator('zod', { throws: true })],
            }),
          },
        },
      });
      const error = await run(cfg, { write: false }).catch((e) => e);
      expect(error).toBeInstanceOf(DriverError);
      expect(error).toMatchObject({
        role: 'generator',
        driverName: 'zod',
        dependencyOf: 'angular',
      });
      expect(error.message).toContain("dependency of 'angular'");
    });

    it('tags a private instance logger with its dependent', async () => {
      const info = vi.fn();
      const zod: Generator = {
        name: 'zod',
        generate: (ctx) => {
          ctx.logger.info('hello');
          return {
            files: [{ path: `pg/${ctx.segment}/index.ts`, content: '//\n' }],
            artifact: { entities: {} },
          };
        },
      };
      await run(
        config({
          generators: {
            angular: { generator: generator('angular', { dependsOn: [zod] }) },
          },
        }),
        {
          write: false,
          logger: { debug() {}, info, warn() {}, error() {} },
        },
      );
      expect(info).toHaveBeenCalledWith('hello', {
        generator: 'zod',
        dependencyOf: 'angular',
      });
    });
  });

  it('rejects before parsing when opts.signal is already aborted', async () => {
    const controller = new AbortController();
    controller.abort();
    let parsed = false;
    const cfg = config({
      sources: {
        pg: {
          parser: {
            name: 'p',
            parse: () => {
              parsed = true;
              return source('pg');
            },
          },
        },
      },
    });
    await expect(run(cfg, { signal: controller.signal })).rejects.toThrow();
    expect(parsed).toBe(false);
  });

  it('a generator emitting <ns>/index.ts collides with the synthesized barrel', async () => {
    const stray: Generator = {
      name: 'zod',
      generate: () => ({
        files: [
          { path: 'pg/zod/user.ts', content: '// user\n' },
          { path: 'pg/index.ts', content: '// stray\n' },
        ],
        artifact: { entities: {} },
      }),
    };
    const cfg = config({ generators: { zod: { generator: stray } } });
    await expect(run(cfg, { write: false })).rejects.toBeInstanceOf(
      OutputCollisionError,
    );
    await expect(run(cfg, { write: false })).rejects.toThrow(
      /<namespace>\/<generatorName>/,
    );
  });

  it('synthesizes a root barrel across two generators on one namespace', async () => {
    const cfg = config({
      generators: {
        zod: { generator: generator('zod') },
        angular: { generator: generator('angular') },
      },
    });
    const result = await run(cfg, { write: false });
    const barrel = result.files.find((f) => f.path === 'pg/index.ts');
    expect(barrel?.content).toBe(
      "// Generated by tako. Do not edit.\nexport * from './angular/index.js';\nexport * from './zod/index.js';\n",
    );
  });

  it('warns once about ambiguous root-barrel exports even with several outputs', async () => {
    const colliding = (name: string): Generator => ({
      name,
      generate: () => ({
        files: [
          { path: `pg/${name}/index.ts`, content: "export * from './User';\n" },
          {
            path: `pg/${name}/User.ts`,
            content: `export const User_${name} = 0;\nexport { User_${name} as User };\n`,
          },
        ],
        artifact: { entities: {} },
      }),
    });
    const warn = vi.fn();
    await run(
      config({
        generators: {
          zod: { generator: colliding('zod') },
          typescript: { generator: colliding('typescript') },
        },
        outputs: [
          { dir: path.join(dir, 'a') },
          { dir: path.join(dir, 'b'), generators: ['zod', 'typescript'] },
        ],
      }),
      { logger: { debug() {}, info() {}, warn, error() {} } },
    );
    const barrelWarnings = warn.mock.calls.filter(([msg]) =>
      String(msg).includes('Name clash in namespace'),
    );
    expect(barrelWarnings).toHaveLength(1);
    expect(barrelWarnings[0]?.[0]).toContain(
      "Name clash in namespace 'pg': typescript and zod each generate a declaration named 'User'.",
    );
  });

  it('two outputs with disjoint generators filters each write only their own subset', async () => {
    const dirA = path.join(dir, 'a');
    const dirB = path.join(dir, 'b');
    const cfg = config({
      generators: {
        zod: { generator: generator('zod') },
        angular: { generator: generator('angular') },
      },
      outputs: [
        { dir: dirA, generators: ['zod'] },
        { dir: dirB, generators: ['zod', 'angular'] },
      ],
    });
    const result = await run(cfg);

    expect(result.written).toHaveLength(2);
    expect(result.written[0]?.output.dir).toBe(dirA);
    expect(result.written[1]?.output.dir).toBe(dirB);

    await expect(fs.access(path.join(dirA, 'pg', 'angular'))).rejects.toThrow();
    expect(await fs.readFile(path.join(dirA, 'pg', 'index.ts'), 'utf8')).toBe(
      "// Generated by tako. Do not edit.\nexport * from './zod/index.js';\n",
    );
    expect(await fs.readFile(path.join(dirB, 'pg', 'index.ts'), 'utf8')).toBe(
      "// Generated by tako. Do not edit.\nexport * from './angular/index.js';\nexport * from './zod/index.js';\n",
    );

    // The full computed tree stays unfiltered regardless of any output's filter.
    expect(result.files.map((f) => f.path).sort()).toEqual([
      'pg/angular/index.ts',
      'pg/index.ts',
      'pg/zod/index.ts',
    ]);
    expect(Object.keys(result.artifacts).sort()).toEqual(['angular', 'zod']);
  });

  it('an output with generators omitted gets every generator that ran', async () => {
    const outDir = path.join(dir, 'out');
    const cfg = config({
      generators: {
        zod: { generator: generator('zod') },
        angular: { generator: generator('angular') },
      },
      outputs: [{ dir: outDir }],
    });
    await run(cfg);
    expect(await fs.readFile(path.join(outDir, 'pg', 'index.ts'), 'utf8')).toBe(
      "// Generated by tako. Do not edit.\nexport * from './angular/index.js';\nexport * from './zod/index.js';\n",
    );
  });

  it('afterEmit fires once per output, in config.outputs order, each call scoped to its own output', async () => {
    const calls: { outputDir: string; files: string[] }[] = [];
    const afterEmit = vi.fn((ctx: { outputDir: string; files: string[] }) => {
      calls.push({ outputDir: ctx.outputDir, files: ctx.files });
    });
    const dirA = path.join(dir, 'a');
    const dirB = path.join(dir, 'b');
    const cfg = config({
      outputs: [{ dir: dirA }, { dir: dirB }],
      hooks: { afterEmit },
    });
    await run(cfg);

    expect(afterEmit).toHaveBeenCalledTimes(2);
    expect(calls[0]?.outputDir).toBe(dirA);
    expect(calls[1]?.outputDir).toBe(dirB);
    expect(calls[0]?.files.every((f) => f.startsWith(dirA))).toBe(true);
    expect(calls[1]?.files.every((f) => f.startsWith(dirB))).toBe(true);
  });

  it('a HookError thrown for output 1 of 2 stops output 2 from being written', async () => {
    const dirA = path.join(dir, 'a');
    const dirB = path.join(dir, 'b');
    let calls = 0;
    const afterEmit = vi.fn(() => {
      calls += 1;
      if (calls === 1) {
        throw new Error('boom');
      }
    });
    const cfg = config({
      outputs: [{ dir: dirA }, { dir: dirB }],
      hooks: { afterEmit },
    });

    await expect(run(cfg)).rejects.toMatchObject({ code: 'hook_error' });
    expect(
      await fs.access(dirA).then(
        () => true,
        () => false,
      ),
    ).toBe(true);
    expect(
      await fs.access(dirB).then(
        () => true,
        () => false,
      ),
    ).toBe(false);
  });

  describe('Parser.anchor', () => {
    function capturingParser(anchor?: Parser['anchor']): {
      parser: Parser;
      seen: () => string | undefined;
    } {
      let anchorDir: string | undefined;
      return {
        seen: () => anchorDir,
        parser: {
          name: 'parser-pg',
          anchor,
          parse: (ctx) => {
            anchorDir = ctx.anchorDir;
            return source('pg');
          },
        },
      };
    }

    it('passes the anchor() result as ctx.anchorDir', async () => {
      const { parser: p, seen } = capturingParser(() => '/anchored/here');
      await run(config({ sources: { pg: { parser: p } } }), { write: false });
      expect(seen()).toBe('/anchored/here');
    });

    it('falls back to rootDir when the parser has no anchor hook', async () => {
      const { parser: p, seen } = capturingParser();
      await run(config({ sources: { pg: { parser: p } } }), { write: false });
      expect(seen()).toBe(dir);
    });

    it('falls back to rootDir when anchor() returns undefined', async () => {
      const { parser: p, seen } = capturingParser(() => undefined);
      await run(config({ sources: { pg: { parser: p } } }), { write: false });
      expect(seen()).toBe(dir);
    });

    it('awaits an async anchor()', async () => {
      const { parser: p, seen } = capturingParser(async () => '/async/anchor');
      await run(config({ sources: { pg: { parser: p } } }), { write: false });
      expect(seen()).toBe('/async/anchor');
    });

    it('receives rootDir as its argument', async () => {
      const arg = vi.fn(() => '/x');
      await run(
        config({
          sources: {
            pg: {
              parser: { name: 'p', anchor: arg, parse: () => source('pg') },
            },
          },
        }),
        { write: false },
      );
      expect(arg).toHaveBeenCalledWith(dir);
    });
  });

  it('passes the generator name as the context segment', async () => {
    let seen: string | undefined;
    const gen: Generator = {
      name: 'zod',
      generate: (ctx) => {
        seen = ctx.segment;
        return {
          files: [{ path: 'pg/zod/index.ts', content: '// zod\n' }],
          artifact: { entities: {} },
        };
      },
    };
    await run(config({ generators: { zod: { generator: gen } } }), {
      write: false,
    });
    expect(seen).toBe('zod');
  });

  it('exposes ref-cycle members to the generator context, namespace-qualified', async () => {
    const cyclic = createSourceIR({ namespace: 'pg', parser: 'fake' })
      .addTypeAlias('Shape', (t) =>
        t.union((u) => u.ref('Group').scalar('int')),
      )
      .addEntity('Group', (e) => {
        e.field('id', (f) => f.scalar('uuid').primary());
        e.field('child', (f) => f.ref('Shape'));
      })
      .build();
    let seen: Set<string> | undefined;
    const gen: Generator = {
      name: 'zod',
      generate: (ctx) => {
        seen = ctx.cycles;
        return {
          files: [{ path: 'pg/zod/index.ts', content: '// zod\n' }],
          artifact: { entities: {} },
        };
      },
    };
    await run(
      config({
        sources: { pg: { parser: { name: 'p', parse: () => cyclic } } },
        generators: { zod: { generator: gen } },
      }),
      { write: false },
    );
    expect(seen).toEqual(new Set(['pg.Shape', 'pg.Group']));
  });

  it('runs a source carrying a typeAliases entry end to end (mode A)', async () => {
    const withAlias = createSourceIR({ namespace: 'pg', parser: 'fake' })
      .addTypeAlias('Metadata', (t) =>
        t.union((u) => u.scalar('string').scalar('int')),
      )
      .addEntity('User', (e) => {
        e.field('id', (f) => f.scalar('uuid').primary());
      })
      .build();
    const zod: Generator = {
      name: 'zod',
      generate: () => ({
        files: [
          {
            path: 'pg/zod/aliases.ts',
            content: 'export type Metadata = string | number;\n',
          },
          { path: 'pg/zod/index.ts', content: "export * from './aliases';\n" },
        ],
        artifact: {
          entities: {
            'pg.Metadata': {
              module: 'pg/zod/aliases',
              symbols: { schema: 'MetadataSchema', type: 'Metadata' },
            },
          },
        },
      }),
    };
    const warn = vi.fn();
    const result = await run(
      config({
        sources: { pg: { parser: { name: 'p', parse: () => withAlias } } },
        generators: { zod: { generator: zod } },
      }),
      { write: false, logger: { debug() {}, info() {}, warn, error() {} } },
    );
    expect(result.files.map((f) => f.path)).toContain('pg/index.ts');
    expect(result.ir.sources.pg?.typeAliases?.Metadata).toBeDefined();
    expect(warn).not.toHaveBeenCalled();
  });
});
