import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { PlannedFile } from '@kurotako/core';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  comparePlanToDisk,
  ignoreBuildArtifacts,
  markedPackageDirs,
} from './diff.js';

let root: string;

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), 'kurotako-diff-'));
});

afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

function write(rel: string, content: string): string {
  const abs = join(root, rel);
  mkdirSync(join(abs, '..'), { recursive: true });
  writeFileSync(abs, content, 'utf8');
  return abs;
}

function plannedFile(rel: string, content: string): PlannedFile {
  return { path: join(root, rel), content };
}

const noIgnore = () => false;

describe('comparePlanToDisk (mode A)', () => {
  it('an identical tree reports nothing', async () => {
    write('out/a.ts', 'a\n');
    write('out/b/c.ts', 'c\n');
    const plan = [
      plannedFile('out/a.ts', 'a\n'),
      plannedFile('out/b/c.ts', 'c\n'),
    ];

    const drift = await comparePlanToDisk({
      plan,
      roots: [join(root, 'out')],
      ignore: noIgnore,
      rootDir: root,
    });
    expect(drift).toEqual([]);
  });

  it('flags an edited file as modified', async () => {
    write('out/a.ts', 'tampered\n');
    const drift = await comparePlanToDisk({
      plan: [plannedFile('out/a.ts', 'a\n')],
      roots: [join(root, 'out')],
      ignore: noIgnore,
      rootDir: root,
    });
    expect(drift).toEqual([{ kind: 'modified', path: 'out/a.ts' }]);
  });

  it('flags a deleted file as missing', async () => {
    mkdirSync(join(root, 'out'), { recursive: true });
    const drift = await comparePlanToDisk({
      plan: [plannedFile('out/a.ts', 'a\n')],
      roots: [join(root, 'out')],
      ignore: noIgnore,
      rootDir: root,
    });
    expect(drift).toEqual([{ kind: 'missing', path: 'out/a.ts' }]);
  });

  it('flags an extra file as orphan', async () => {
    write('out/a.ts', 'a\n');
    write('out/stray.ts', 'stray\n');
    const drift = await comparePlanToDisk({
      plan: [plannedFile('out/a.ts', 'a\n')],
      roots: [join(root, 'out')],
      ignore: noIgnore,
      rootDir: root,
    });
    expect(drift).toEqual([{ kind: 'orphan', path: 'out/stray.ts' }]);
  });

  it('collapses a wholly-orphan subdirectory to a single entry', async () => {
    write('out/a.ts', 'a\n');
    write('out/legacy/one.ts', '1\n');
    write('out/legacy/nested/two.ts', '2\n');
    const drift = await comparePlanToDisk({
      plan: [plannedFile('out/a.ts', 'a\n')],
      roots: [join(root, 'out')],
      ignore: noIgnore,
      rootDir: root,
    });
    expect(drift).toEqual([{ kind: 'orphan', path: 'out/legacy/' }]);
  });

  it('sorts entries by path then kind', async () => {
    write('out/z.ts', 'tampered\n');
    write('out/extra.ts', 'x\n');
    const drift = await comparePlanToDisk({
      plan: [plannedFile('out/z.ts', 'z\n'), plannedFile('out/y.ts', 'y\n')],
      roots: [join(root, 'out')],
      ignore: noIgnore,
      rootDir: root,
    });
    expect(drift).toEqual([
      { kind: 'orphan', path: 'out/extra.ts' },
      { kind: 'missing', path: 'out/y.ts' },
      { kind: 'modified', path: 'out/z.ts' },
    ]);
  });
});

describe('comparePlanToDisk (mode B)', () => {
  it('ignores dist/ and node_modules/, flags a stale marked package once, spares a hand-written one', async () => {
    // Owned package, in sync.
    write(
      'packages/acme-pg/package.json',
      '{\n  "//": "Generated by tako. Do not edit."\n}\n',
    );
    write('packages/acme-pg/src/index.ts', 'export {}\n');
    write('packages/acme-pg/dist/index.js', 'build output\n');
    write('packages/acme-pg/node_modules/dep/index.js', 'dep\n');
    // Stale marked package: no namespace in the config any more.
    write(
      'packages/acme-legacy/package.json',
      '{\n  "//": "Generated by tako. Do not edit."\n}\n',
    );
    write('packages/acme-legacy/src/old.ts', 'old\n');
    // Hand-written package: no marker.
    write('packages/acme-manual/package.json', '{ "name": "acme-manual" }\n');
    write('packages/acme-manual/src/hand.ts', 'hand\n');

    const packagesDir = join(root, 'packages');
    const roots = await markedPackageDirs(packagesDir);
    expect(roots).toEqual([
      join(packagesDir, 'acme-legacy'),
      join(packagesDir, 'acme-pg'),
    ]);

    const plan = [
      plannedFile(
        'packages/acme-pg/package.json',
        '{\n  "//": "Generated by tako. Do not edit."\n}\n',
      ),
      plannedFile('packages/acme-pg/src/index.ts', 'export {}\n'),
    ];

    const drift = await comparePlanToDisk({
      plan,
      roots,
      ignore: ignoreBuildArtifacts,
      rootDir: root,
    });
    expect(drift).toEqual([{ kind: 'orphan', path: 'packages/acme-legacy/' }]);
  });
});

describe('ignoreBuildArtifacts', () => {
  it('rejects dist and node_modules segments only', () => {
    expect(ignoreBuildArtifacts('/a/dist/x.js')).toBe(true);
    expect(ignoreBuildArtifacts('/a/node_modules/x/y.js')).toBe(true);
    expect(ignoreBuildArtifacts('/a/src/dist.ts')).toBe(false);
    expect(ignoreBuildArtifacts('/a/src/index.ts')).toBe(false);
  });
});
