/**
 * `comparePlanToDisk` — the in-memory comparison behind `tako check`. Takes the
 * `PlannedFile[]` a fresh `generate` would write (from `run({ plan: true })`)
 * and reports every way the tree on disk diverges from it: a planned file that
 * is absent (`missing`) or whose bytes differ (`modified`), and any file under
 * the scanned roots that no planned file claims (`orphan`).
 *
 * Design: `backlog/features/drift-guard/technical.md` §The comparison.
 */
import { existsSync } from 'node:fs';
import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import type { PlannedFile } from '@kurotako/core';

export type DriftKind = 'modified' | 'missing' | 'orphan';

export interface DriftEntry {
  kind: DriftKind;
  /** Relative to `rootDir`, POSIX separators; a collapsed dir ends with `/`. */
  path: string;
}

export interface ComparePlanToDiskArgs {
  plan: PlannedFile[];
  /** Directories walked for orphans (absolute). */
  roots: string[];
  /** Return `true` to exclude an absolute path from the orphan scan. */
  ignore: (absPath: string) => boolean;
  /** Anchor for the reported relative paths (the config-file directory). */
  rootDir: string;
}

function toPosix(rootDir: string, absPath: string): string {
  return path.relative(rootDir, absPath).split(path.sep).join('/');
}

export async function comparePlanToDisk(
  args: ComparePlanToDiskArgs,
): Promise<DriftEntry[]> {
  const { plan, roots, ignore, rootDir } = args;
  const plannedByPath = new Map(plan.map((f) => [path.resolve(f.path), f]));
  const entries: DriftEntry[] = [];

  // 1. Expected vs disk.
  for (const [absPath, file] of plannedByPath) {
    if (!existsSync(absPath)) {
      entries.push({ kind: 'missing', path: toPosix(rootDir, absPath) });
      continue;
    }
    const onDisk = await readFile(absPath, 'utf8');
    if (onDisk !== file.content) {
      entries.push({ kind: 'modified', path: toPosix(rootDir, absPath) });
    }
  }

  // 2. Orphan scan — a planned file lives under `dir` iff any planned absolute
  // path is `dir` itself or sits below it.
  const plannedPaths = [...plannedByPath.keys()];
  const hasPlannedUnder = (dir: string): boolean => {
    const prefix = `${dir}${path.sep}`;
    return plannedPaths.some((p) => p === dir || p.startsWith(prefix));
  };

  const seenRoots = new Set<string>();
  for (const root of roots) {
    const absRoot = path.resolve(root);
    if (seenRoots.has(absRoot) || !existsSync(absRoot)) {
      continue;
    }
    seenRoots.add(absRoot);
    await scan(absRoot);
  }

  async function scan(dir: string): Promise<void> {
    // A directory with no planned file underneath collapses to a single entry —
    // unless it holds nothing but ignored files (e.g. only `dist/`).
    if (!hasPlannedUnder(dir)) {
      if (await hasNonIgnoredFile(dir)) {
        entries.push({ kind: 'orphan', path: `${toPosix(rootDir, dir)}/` });
      }
      return;
    }
    for (const dirent of await readdir(dir, { withFileTypes: true })) {
      const abs = path.join(dir, dirent.name);
      if (ignore(abs)) {
        continue;
      }
      if (dirent.isDirectory()) {
        await scan(abs);
      } else if (dirent.isFile() && !plannedByPath.has(abs)) {
        entries.push({ kind: 'orphan', path: toPosix(rootDir, abs) });
      }
    }
  }

  async function hasNonIgnoredFile(dir: string): Promise<boolean> {
    for (const dirent of await readdir(dir, { withFileTypes: true })) {
      const abs = path.join(dir, dirent.name);
      if (ignore(abs)) {
        continue;
      }
      if (dirent.isFile()) {
        return true;
      }
      if (dirent.isDirectory() && (await hasNonIgnoredFile(abs))) {
        return true;
      }
    }
    return false;
  }

  entries.sort((a, b) =>
    a.path < b.path
      ? -1
      : a.path > b.path
        ? 1
        : a.kind < b.kind
          ? -1
          : a.kind > b.kind
            ? 1
            : 0,
  );
  return entries;
}

/** Rejects `dist/` and `node_modules/` anywhere in the path (mode B). */
export function ignoreBuildArtifacts(absPath: string): boolean {
  return /(^|[/\\])(dist|node_modules)([/\\]|$)/.test(absPath);
}

/**
 * Whether `<packagesDir>/<name>` looks like a directory `tako` generated: a
 * `package.json` whose `"//"` marker starts with `Generated by tako`.
 */
export async function hasGeneratedMarker(pkgDir: string): Promise<boolean> {
  try {
    const pkg = JSON.parse(
      await readFile(path.join(pkgDir, 'package.json'), 'utf8'),
    ) as { '//'?: unknown };
    return (
      typeof pkg['//'] === 'string' && pkg['//'].startsWith('Generated by tako')
    );
  } catch {
    return false;
  }
}

/** Every immediate subdirectory of `packagesDir` carrying the tako marker. */
export async function markedPackageDirs(
  packagesDir: string,
): Promise<string[]> {
  if (!existsSync(packagesDir)) {
    return [];
  }
  const out: string[] = [];
  for (const dirent of await readdir(packagesDir, { withFileTypes: true })) {
    if (!dirent.isDirectory()) {
      continue;
    }
    const abs = path.join(packagesDir, dirent.name);
    if (await hasGeneratedMarker(abs)) {
      out.push(abs);
    }
  }
  return out.sort();
}
