/**
 * The generated-file banner. `run.ts` calls `applyBanner` once, after barrel
 * synthesis and before the writer, so every `.ts` file — generator output and
 * synthesized barrels alike — carries the marker. `.json` files have no comment
 * syntax: `packageWriter` sets a `"//"` key on `package.json` instead.
 *
 * Design: `backlog/features/output-modes/technical.md` §Banner.
 */
import type { VirtualFile } from '../types.js';

export const BANNER = '// Generated by tako. Do not edit.\n';
export const GITATTRIBUTES = '* linguist-generated=true\n';

/** Basenames that take the comment-form banner despite a non-`.ts` extension. */
const COMMENTABLE_BASENAMES = new Set(['tsconfig.json']);

function takesBanner(path: string): boolean {
  if (path.endsWith('.ts') || path.endsWith('.tsx')) {
    return true;
  }
  const basename = path.slice(path.lastIndexOf('/') + 1);
  return COMMENTABLE_BASENAMES.has(basename);
}

/**
 * Prepend `BANNER` to every `.ts` / `.tsx` file (and `tsconfig.json`). Pure,
 * and idempotent-safe: a file that already starts with the banner is left
 * untouched. `package.json` and other `.json` files pass through unchanged.
 */
export function applyBanner(files: VirtualFile[]): VirtualFile[] {
  return files.map((file) => {
    if (!takesBanner(file.path) || file.content.startsWith(BANNER)) {
      return file;
    }
    return { path: file.path, content: BANNER + file.content };
  });
}
