import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import {
  MissingPackageWorkspaceFilesError,
  OutputNotGeneratedError,
  PackageBuildError,
} from '../errors.js';
import type { GeneratorArtifact, Logger, VirtualFile } from '../types.js';
import { packageWriter } from './package.js';
import { runInstall } from './pm.js';

const build = vi.hoisted(() => vi.fn());

vi.mock('tsup', () => ({ build }));

vi.mock('./pm.js', async (importOriginal) => {
  const actual = await importOriginal<typeof import('./pm.js')>();
  return { ...actual, runInstall: vi.fn().mockResolvedValue(undefined) };
});

function logger(): Logger {
  return { debug: vi.fn(), info: vi.fn(), warn: vi.fn(), error: vi.fn() };
}

const files: VirtualFile[] = [
  {
    path: 'pg/index.ts',
    content: "// Generated by tako. Do not edit.\nexport * from './zod';\n",
  },
  { path: 'pg/zod/index.ts', content: 'export * from "./enums";\n' },
  { path: 'pg/zod/enums.ts', content: 'export const Role = 1;\n' },
];

const artifacts: Record<string, GeneratorArtifact> = {
  zod: { entities: {}, peerDependencies: { zod: '^4' } },
};

async function stubResolvableTypescript(workspaceRoot: string): Promise<void> {
  const tsDir = path.join(workspaceRoot, 'node_modules', 'typescript');
  await fs.mkdir(tsDir, { recursive: true });
  await fs.writeFile(
    path.join(tsDir, 'package.json'),
    '{"name":"typescript","main":"index.js"}',
    'utf8',
  );
  await fs.writeFile(path.join(tsDir, 'index.js'), '', 'utf8');
}

let dir: string;

beforeEach(async () => {
  dir = await fs.mkdtemp(path.join(os.tmpdir(), 'kurotako-pkg-'));
  await fs.writeFile(path.join(dir, '.git'), '', 'utf8');
  await fs.writeFile(path.join(dir, 'tsconfig.base.json'), '{}', 'utf8');
  await fs.writeFile(path.join(dir, 'tsup.config.base.ts'), '', 'utf8');
  await stubResolvableTypescript(dir);
  build.mockReset();
  build.mockResolvedValue(undefined);
  vi.mocked(runInstall).mockClear();
  vi.mocked(runInstall).mockResolvedValue(undefined);
});

afterEach(async () => {
  await fs.rm(dir, { recursive: true, force: true });
});

function write(overrides?: { packageManager?: 'bun' | 'npm' }) {
  return packageWriter.write({
    files,
    artifacts,
    logger: logger(),
    output: {
      mode: 'package',
      packagesDir: path.join(dir, 'packages'),
      scope: '@kurotako',
      ...overrides,
    },
  });
}

describe('packageWriter', () => {
  it('lays out one package per namespace with the prefix stripped', async () => {
    await write({ packageManager: 'bun' });
    const pkgDir = path.join(dir, 'packages', 'kurotako-pg');
    expect(
      await fs.readFile(path.join(pkgDir, 'src/index.ts'), 'utf8'),
    ).toContain("export * from './zod'");
    expect(
      await fs.readFile(path.join(pkgDir, 'src/zod/enums.ts'), 'utf8'),
    ).toBe('export const Role = 1;\n');

    const pkg = JSON.parse(
      await fs.readFile(path.join(pkgDir, 'package.json'), 'utf8'),
    );
    expect(pkg.name).toBe('@kurotako/pg');
    expect(pkg.version).toBe('0.0.0');
    expect(pkg.peerDependencies).toEqual({ zod: '^4' });
    expect(pkg['//']).toBe('Generated by tako. Do not edit.');
    expect(pkg.exports['.']).toBeDefined();
    expect(pkg.exports['./*']).toBeDefined();

    const tsconfig = await fs.readFile(
      path.join(pkgDir, 'tsconfig.json'),
      'utf8',
    );
    expect(tsconfig).toMatch(/^\/\/ Generated by tako/);
    expect(
      JSON.parse(tsconfig.replace(/^\/\/.*\n/, '')).compilerOptions.paths,
    ).toEqual({ 'pg/*': ['./src/*'] });
    expect(
      await fs.readFile(path.join(pkgDir, 'tsup.config.ts'), 'utf8'),
    ).toMatch(/^\/\/ Generated by tako/);
    expect(await fs.readFile(path.join(pkgDir, '.gitattributes'), 'utf8')).toBe(
      '* linguist-generated=true\n',
    );
  });

  it('returns sorted absolute source paths and never dist/', async () => {
    const written = await write({ packageManager: 'bun' });
    expect(written).toEqual([...written].sort());
    expect(written.every((p) => path.isAbsolute(p))).toBe(true);
    expect(written.some((p) => p.includes(`${path.sep}dist${path.sep}`))).toBe(
      false,
    );
  });

  it('invokes the build once per package and the install once', async () => {
    await write({ packageManager: 'bun' });
    expect(build).toHaveBeenCalledTimes(1);
    expect(vi.mocked(runInstall)).toHaveBeenCalledTimes(1);
    expect(vi.mocked(runInstall).mock.calls[0]?.[0]).toBe('bun');
  });

  it('wraps a build failure in PackageBuildError', async () => {
    build.mockRejectedValueOnce(new Error('tsup boom'));
    await expect(write({ packageManager: 'bun' })).rejects.toBeInstanceOf(
      PackageBuildError,
    );
  });

  it('skips the install and warns when no package manager resolves', async () => {
    const log = logger();
    await packageWriter.write({
      files,
      artifacts,
      logger: log,
      output: {
        mode: 'package',
        packagesDir: path.join(dir, 'packages'),
        scope: '@kurotako',
      },
    });
    expect(vi.mocked(runInstall)).not.toHaveBeenCalled();
    expect(log.warn).toHaveBeenCalledTimes(1);
  });

  it('refuses a pre-existing unmarked non-empty package directory', async () => {
    const pkgDir = path.join(dir, 'packages', 'kurotako-pg');
    await fs.mkdir(pkgDir, { recursive: true });
    await fs.writeFile(
      path.join(pkgDir, 'package.json'),
      JSON.stringify({ name: 'hand-written' }),
      'utf8',
    );
    await expect(write({ packageManager: 'bun' })).rejects.toBeInstanceOf(
      OutputNotGeneratedError,
    );
  });

  it('throws MissingPackageWorkspaceFilesError instead of a raw build failure when the workspace base files are absent', async () => {
    await fs.rm(path.join(dir, 'tsconfig.base.json'));
    await fs.rm(path.join(dir, 'tsup.config.base.ts'));
    const error = await write({ packageManager: 'bun' }).catch((e) => e);
    expect(error).toBeInstanceOf(MissingPackageWorkspaceFilesError);
    expect((error as MissingPackageWorkspaceFilesError).missing).toEqual([
      'tsconfig.base.json',
      'tsup.config.base.{ts,js,mjs,cjs}',
    ]);
    expect(build).not.toHaveBeenCalled();
  });

  it('throws MissingPackageWorkspaceFilesError when typescript is not resolvable from the workspace root', async () => {
    await fs.rm(path.join(dir, 'node_modules'), { recursive: true });
    const error = await write({ packageManager: 'bun' }).catch((e) => e);
    expect(error).toBeInstanceOf(MissingPackageWorkspaceFilesError);
    expect((error as MissingPackageWorkspaceFilesError).missing).toEqual([
      "'typescript' (devDependency, needed for the .d.ts build)",
    ]);
  });

  it('accepts a tsup.config.base with a .js extension', async () => {
    await fs.rm(path.join(dir, 'tsup.config.base.ts'));
    await fs.writeFile(path.join(dir, 'tsup.config.base.js'), '', 'utf8');
    await expect(write({ packageManager: 'bun' })).resolves.toBeDefined();
  });

  it('plan() strips the <ns>/ prefix, synthesizes the manifest, and spawns nothing', async () => {
    const mkdir = vi.spyOn(fs, 'mkdir');
    const writeFile = vi.spyOn(fs, 'writeFile');

    const planned = await packageWriter.plan({
      files,
      artifacts,
      logger: logger(),
      output: {
        mode: 'package',
        packagesDir: path.join(dir, 'packages'),
        scope: '@kurotako',
      },
    });

    const pkgDir = path.join(dir, 'packages', 'kurotako-pg');
    const byPath = new Map(planned.map((p) => [p.path, p.content]));

    expect(byPath.has(path.join(pkgDir, 'src/index.ts'))).toBe(true);
    expect(byPath.get(path.join(pkgDir, 'src/zod/enums.ts'))).toBe(
      'export const Role = 1;\n',
    );
    expect(byPath.has(path.join(pkgDir, 'package.json'))).toBe(true);
    expect(byPath.has(path.join(pkgDir, 'tsconfig.json'))).toBe(true);
    expect(byPath.has(path.join(pkgDir, 'tsup.config.ts'))).toBe(true);
    expect(byPath.has(path.join(pkgDir, '.gitattributes'))).toBe(true);
    expect(byPath.has(path.join(dir, 'packages', '.gitattributes'))).toBe(true);

    const pkg = JSON.parse(
      byPath.get(path.join(pkgDir, 'package.json')) as string,
    );
    expect(pkg.version).toBe('0.0.0');
    expect(pkg.peerDependencies).toEqual({ zod: '^4' });

    expect(
      planned.some((p) => p.path.includes(`${path.sep}dist${path.sep}`)),
    ).toBe(false);
    expect(planned.map((p) => p.path)).toEqual(
      [...planned.map((p) => p.path)].sort(),
    );
    expect(build).not.toHaveBeenCalled();
    expect(vi.mocked(runInstall)).not.toHaveBeenCalled();
    expect(mkdir).not.toHaveBeenCalled();
    expect(writeFile).not.toHaveBeenCalled();

    mkdir.mockRestore();
    writeFile.mockRestore();
  });

  it('plan() is byte-identical to the src/ + manifest files write() produces', async () => {
    const output = {
      mode: 'package' as const,
      packagesDir: path.join(dir, 'packages'),
      scope: '@kurotako',
      packageManager: 'bun' as const,
    };
    const planned = await packageWriter.plan({ files, artifacts, output });
    await packageWriter.write({ files, artifacts, logger: logger(), output });

    for (const entry of planned) {
      expect(await fs.readFile(entry.path, 'utf8')).toBe(entry.content);
    }
  });

  it('plan() is deterministic across calls', async () => {
    const input = {
      files,
      artifacts,
      output: {
        mode: 'package' as const,
        packagesDir: path.join(dir, 'packages'),
        scope: '@kurotako',
      },
    };
    expect(await packageWriter.plan(input)).toEqual(
      await packageWriter.plan(input),
    );
  });

  it('overwrites a previously generated package and is byte-deterministic', async () => {
    const first = await write({ packageManager: 'bun' });
    const pkgDir = path.join(dir, 'packages', 'kurotako-pg');
    const pkgJson1 = await fs.readFile(
      path.join(pkgDir, 'package.json'),
      'utf8',
    );
    const second = await write({ packageManager: 'bun' });
    const pkgJson2 = await fs.readFile(
      path.join(pkgDir, 'package.json'),
      'utf8',
    );
    expect(second).toEqual(first);
    expect(pkgJson2).toBe(pkgJson1);
  });
});
