/**
 * Mode B writer: one npm package per namespace under `output.packagesDir`.
 * `packageWriter` writes the sources, synthesizes `package.json` /
 * `tsconfig.json` / `tsup.config.ts`, builds each package with a lazily loaded
 * `tsup`, then runs `<pm> install` once to link them.
 *
 * `tsup` is a `dependencies` of `@kurotako/core` but imported with
 * `await import('tsup')` so a mode-A run never resolves it.
 *
 * Design: `backlog/features/output-modes/technical.md` §`packageWriter` (mode B).
 */
import { existsSync, readFileSync } from 'node:fs';
import fs from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';
import {
  MissingPackageWorkspaceFilesError,
  OutputNotGeneratedError,
  PackageBuildError,
  TakoError,
} from '../errors.js';
import { noopLogger } from '../logger.js';
import type { VirtualFile } from '../types.js';
import { BANNER, GITATTRIBUTES } from './banner.js';
import { collectPeerDependencies } from './peers.js';
import { ancestors, resolvePackageManager, runInstall } from './pm.js';
import type { Writer } from './types.js';

const MARKER = 'Generated by tako. Do not edit.';

export const packageWriter: Writer = {
  async write({ files, output, artifacts, logger = noopLogger }) {
    if (!output.packagesDir) {
      throw new TakoError(
        'invalid_output_config',
        "mode 'package' requires 'output.packagesDir'",
      );
    }
    if (!output.scope) {
      throw new TakoError(
        'invalid_output_config',
        "mode 'package' requires 'output.scope'",
      );
    }

    const packagesDir = path.resolve(output.packagesDir);
    const scope = output.scope;
    const scopeSlug = scope.replace(/^@/, '');
    assertWorkspaceBaseFiles(packagesDir);
    const peersByNamespace = collectPeerDependencies(artifacts ?? {}, files);

    const byNamespace = new Map<string, VirtualFile[]>();
    for (const file of files) {
      const slash = file.path.indexOf('/');
      if (slash === -1) {
        continue;
      }
      const namespace = file.path.slice(0, slash);
      const rest = file.path.slice(slash + 1);
      const list = byNamespace.get(namespace) ?? [];
      list.push({ path: rest, content: file.content });
      byNamespace.set(namespace, list);
    }

    const namespaces = [...byNamespace.keys()].sort();
    await fs.mkdir(packagesDir, { recursive: true });
    const written: string[] = [];
    const entriesByNamespace = new Map<string, string[]>();

    for (const namespace of namespaces) {
      const sources = [...(byNamespace.get(namespace) ?? [])].sort((a, b) =>
        a.path < b.path ? -1 : a.path > b.path ? 1 : 0,
      );
      const pkgDir = path.join(packagesDir, `${scopeSlug}-${namespace}`);
      await guardAndReset(pkgDir);

      const entries: string[] = [];
      for (const src of sources) {
        const absolute = path.join(pkgDir, 'src', src.path);
        await fs.mkdir(path.dirname(absolute), { recursive: true });
        await fs.writeFile(absolute, src.content, 'utf8');
        written.push(absolute);
        entries.push(`src/${src.path}`);
      }

      const pkgJsonPath = path.join(pkgDir, 'package.json');
      await fs.writeFile(
        pkgJsonPath,
        buildPackageJson(scope, namespace, peersByNamespace[namespace] ?? {}),
        'utf8',
      );
      written.push(pkgJsonPath);

      const tsconfigPath = path.join(pkgDir, 'tsconfig.json');
      await fs.writeFile(tsconfigPath, buildTsconfig(), 'utf8');
      written.push(tsconfigPath);

      const sortedEntries = entries.sort();
      entriesByNamespace.set(namespace, sortedEntries);
      const tsupPath = path.join(pkgDir, 'tsup.config.ts');
      await fs.writeFile(tsupPath, buildTsupConfig(sortedEntries), 'utf8');
      written.push(tsupPath);

      const gitattributesPath = path.join(pkgDir, '.gitattributes');
      await fs.writeFile(gitattributesPath, GITATTRIBUTES, 'utf8');
      written.push(gitattributesPath);
    }

    const rootGitattributes = path.join(packagesDir, '.gitattributes');
    await fs.writeFile(
      rootGitattributes,
      `${scopeSlug}-*/** linguist-generated=true\n`,
      'utf8',
    );
    written.push(rootGitattributes);

    await buildPackages(packagesDir, scopeSlug, namespaces, entriesByNamespace);

    const pm = resolvePackageManager({
      configured: output.packageManager,
      startDir: packagesDir,
    });
    if (pm) {
      await runInstall(pm, findWorkspaceRoot(packagesDir) ?? packagesDir);
    } else {
      logger.warn(
        "could not resolve a package manager; run '<your package manager> install' in the workspace root to link the generated packages",
        { packagesDir },
      );
    }

    return written.sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
  },
};

const TSUP_CONFIG_BASE_EXTENSIONS = ['.ts', '.js', '.mjs', '.cjs'];

/**
 * The generated `tsconfig.json` / `tsup.config.ts` reference `../../tsconfig.base.json`
 * / `../../tsup.config.base` (two levels up from `<pkgDir>`, i.e. one level up from
 * `packagesDir`). Failing fast here turns an opaque esbuild "Could not resolve" into
 * an actionable error naming exactly what's missing and where.
 */
function assertWorkspaceBaseFiles(packagesDir: string): void {
  const workspaceRoot = path.dirname(packagesDir);
  const missing: string[] = [];

  if (!existsSync(path.join(workspaceRoot, 'tsconfig.base.json'))) {
    missing.push('tsconfig.base.json');
  }
  const hasTsupBase = TSUP_CONFIG_BASE_EXTENSIONS.some((ext) =>
    existsSync(path.join(workspaceRoot, `tsup.config.base${ext}`)),
  );
  if (!hasTsupBase) {
    missing.push('tsup.config.base.{ts,js,mjs,cjs}');
  }
  if (!isResolvableFrom('typescript', workspaceRoot)) {
    missing.push("'typescript' (devDependency, needed for the .d.ts build)");
  }

  if (missing.length > 0) {
    throw new MissingPackageWorkspaceFilesError(workspaceRoot, missing);
  }
}

function isResolvableFrom(specifier: string, from: string): boolean {
  try {
    createRequire(path.join(from, 'noop.js')).resolve(specifier);
    return true;
  } catch {
    return false;
  }
}

async function guardAndReset(pkgDir: string): Promise<void> {
  let entries: string[];
  try {
    entries = await fs.readdir(pkgDir);
  } catch {
    entries = [];
  }

  if (entries.length > 0 && !hasGeneratedMarker(pkgDir)) {
    throw new OutputNotGeneratedError(pkgDir);
  }

  await fs.rm(pkgDir, { recursive: true, force: true });
  await fs.mkdir(pkgDir, { recursive: true });
}

function hasGeneratedMarker(pkgDir: string): boolean {
  try {
    const pkg = JSON.parse(
      readFileSync(path.join(pkgDir, 'package.json'), 'utf8'),
    ) as { '//'?: unknown };
    return (
      typeof pkg['//'] === 'string' && pkg['//'].startsWith('Generated by tako')
    );
  } catch {
    return false;
  }
}

async function buildPackages(
  packagesDir: string,
  scopeSlug: string,
  namespaces: string[],
  entriesByNamespace: Map<string, string[]>,
): Promise<void> {
  const { build } = await import('tsup');
  const originalCwd = process.cwd();
  try {
    for (const namespace of namespaces) {
      const pkgDir = path.join(packagesDir, `${scopeSlug}-${namespace}`);
      // Still needed: tsup/esbuild auto-detects `peerDependencies` (e.g. `zod`)
      // as external by reading the nearest `package.json`, which it locates
      // from `process.cwd()`.
      process.chdir(pkgDir);
      try {
        await build({
          // Config auto-discovery (cosmiconfig) is disabled: the pkgDir's own
          // tsup.config.ts exists for humans building the package standalone
          // later, but resolving it here — a TS file re-exporting
          // `../../tsup.config.base` — through tsup's config loader instead of
          // this programmatic call caused spurious "Could not resolve" entry
          // errors.
          config: false,
          // A relative `entry` array goes through tinyglobby, whose matches
          // esbuild then resolves against the cwd esbuild's service captured
          // at first use — *not* the cwd at this call, so it silently breaks
          // after the first `process.chdir()` in this loop. An absolute-path
          // entry *map* skips glob resolution entirely (tsup only runs
          // `fs.existsSync` on it) and keeps `dist/` mirroring `src/`.
          entry: Object.fromEntries(
            (entriesByNamespace.get(namespace) ?? []).map((entry) => [
              entry.replace(/^src\//, '').replace(/\.ts$/, ''),
              path.join(pkgDir, entry),
            ]),
          ),
          tsconfig: path.join(pkgDir, 'tsconfig.json'),
          format: ['esm', 'cjs'],
          dts: { compilerOptions: { composite: false, incremental: false } },
          outDir: path.join(pkgDir, 'dist'),
          silent: true,
        });
      } catch (cause) {
        throw new PackageBuildError(namespace, { cause });
      }
    }
  } finally {
    process.chdir(originalCwd);
  }
}

function findWorkspaceRoot(startDir: string): string | null {
  for (const dir of ancestors(startDir)) {
    if (existsSync(path.join(dir, 'pnpm-workspace.yaml'))) {
      return dir;
    }
    const pkgPath = path.join(dir, 'package.json');
    if (existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as {
          workspaces?: unknown;
        };
        if (pkg.workspaces !== undefined) {
          return dir;
        }
      } catch {
        // keep walking
      }
    }
  }
  return null;
}

function buildPackageJson(
  scope: string,
  namespace: string,
  peerDependencies: Record<string, string>,
): string {
  const pkg = {
    name: `${scope}/${namespace}`,
    version: '0.0.0',
    type: 'module',
    main: './dist/index.cjs',
    module: './dist/index.js',
    types: './dist/index.d.ts',
    exports: {
      '.': {
        types: './dist/index.d.ts',
        import: './dist/index.js',
        require: './dist/index.cjs',
      },
      './*': {
        types: './dist/*.d.ts',
        import: './dist/*.js',
        require: './dist/*.cjs',
      },
    },
    files: ['dist', 'src'],
    peerDependencies,
    sideEffects: false,
    scripts: { build: 'tsup' },
    '//': MARKER,
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

function buildTsconfig(): string {
  const body = JSON.stringify(
    {
      extends: '../../tsconfig.base.json',
      compilerOptions: { outDir: 'dist' },
      include: ['src'],
    },
    null,
    2,
  );
  return `${BANNER}${body}\n`;
}

function buildTsupConfig(entries: string[]): string {
  const list = entries.map((entry) => `    '${entry}',`).join('\n');
  return `${BANNER}import { basePreset } from '../../tsup.config.base';

export default {
  ...basePreset,
  entry: [
${list}
  ],
};
`;
}
